"""empty message

Revision ID: e4f783f83ca1
Revises: 00eec767b4ae
Create Date: 2022-12-07 04:47:08.370505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4f783f83ca1'
down_revision = '00eec767b4ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Auditorium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=45), nullable=True),
    sa.Column('price_per_hour', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('surname', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('auditorium_id', sa.Integer(), nullable=True),
    sa.Column('reservation_start', sa.DATETIME(), nullable=True),
    sa.Column('hours_ordered', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auditorium_id'], ['Auditorium.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('auditorium')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditorium',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seats', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('price_per_hour', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('surname', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auditorium_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reservation_start', mysql.DATETIME(), nullable=True),
    sa.Column('hours_ordered', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['auditorium_id'], ['auditorium.id'], name='order_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='order_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('Order')
    op.drop_table('User')
    op.drop_table('Auditorium')
    # ### end Alembic commands ###
